
# SPRING
spring:
  profiles:
    active: dev
  main:
    banner-mode: off
  redis:
    timeout: 10s
    database: 0
  mail:
    host: smtp.163.com
    username: vcrting@163.com
    password: AMPKRPNFKXZIJHOO
    default-encoding: utf-8
  mvc:
    static-path-pattern: /uploads/**
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

# 日誌級別
logging:
  level:
    root: error

# MyBatis Plus
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    db-config:
      id-type: assign_id
      table-underline: false # 去除表名驼峰方式
  configuration:
    # 关闭 驼峰
    map-underscore-to-camel-case: false