
# SPRING
spring:
  profiles:
    active: dev
  main:
    banner-mode: off
  rabbitmq:
    connection-timeout: 1s
    listener:
      simple:
        prefetch: 1 # 每次 取 一個，消費完 才去 申請下一個
  redis:
    timeout: 10s
    database: 0
  mail:
    host: smtp.163.com
    username: vcrting@163.com
    password: AMPKRPNFKXZIJHOO
    default-encoding: utf-8
  mvc:
    static-path-pattern: /uploads/**
  web:
    resources:
      static-locations: classpath:/xlsx/
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

# 日誌級別
logging:
  level:
    root: error

# MyBatis Plus
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml, classpath*:mapperMulti/**/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
      table-underline: false # 去除表名驼峰方式
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    # 关闭 驼峰
    map-underscore-to-camel-case: false