
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://42.192.15.218:3306/yc_study?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: qiong
    password: qiong

    dynamic:
      datasource:
        master:
          url: jdbc:mysql://42.192.15.218:3306/yc_master?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: qiong
          password: qiong
        multi-one:
          url: jdbc:mysql://42.192.15.218:3306/yc_study?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: qiong
          password: qiong
        multi-two:
          url: jdbc:mysql://42.192.15.218:3306/yc_study_x2?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: qiong
          password: qiong

logging:
  level:
    root: info

mybatis-plus:
  configuration:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 登录 = /camunda/app/welcome/default/#!/login
camunda.bpm:
  admin-user:
    id: admin  #用户名
    password: 123  #密码
    firstName: Zeng
  filter:
    create: All tasks
